const words = {
    nl: [
        'Shoe',
        'Door',
        'Christmas Tree',
        'Moon',
        'Eyes',
        'Spider',
        'Snow',
        'Drum',
        'Shirt',
        'Sad',
        'Doll',
        'Cup',
        'Fish',
        'Sandwich',
        'Cookie',
        'Socks',
        'Book',
        'Pants',
        'Happy',
        'Roof',
        'Candy',
        'Skateboard',
        'Sun',
        'Water',
        'Bed',
        'Hat',
        'Dress',
        'Bubbles',
        'Ocean',
        'Ball',
        'Banana',
        'Butterfly',
        'Cupcake',
        'Rainbow',
        'Grapes',
        'Pizza',
        'House',
        'Sleep',
        'Egg',
        'Bird',
        'Octopus',
        'Star',
        'Coffee',
        'Apple',
        'Mailbox',
        'Nose',
        'Tree',
        'Cat',
        'Leg',
        'Lips',
        'Cloud',
    ]
};

export default words;
